import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#adc6ff',
        'surface-container-highest': '#353534',
        'background': '#131313',
        'surface-container-low': '#1c1b1b',
        'tertiary': '#ffb786',
        'tertiary-container': '#df7412',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-container': '#00285d',
        'on-secondary-container': '#003f38',
        'tertiary-fixed': '#ffdcc6',
        'secondary-container': '#04b4a2',
        'on-secondary': '#003731',
        'surface-container': '#201f1f',
        'primary': '#adc6ff',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'on-tertiary-fixed': '#311400',
        'on-error-container': '#ffdad6',
        'primary-container': '#4d8eff',
        'on-secondary-fixed': '#00201c',
        'secondary': '#4fdbc8',
        'on-primary-fixed-variant': '#004395',
        'outline-variant': '#424754',
        'on-primary': '#002e6a',
        'inverse-primary': '#005ac2',
        'error': '#ffb4ab',
        'surface-variant': '#353534',
        'on-tertiary-container': '#461f00',
        'primary-fixed': '#d8e2ff',
        'on-error': '#690005',
        'on-surface': '#e5e2e1',
        'on-primary-fixed': '#001a42',
        'inverse-on-surface': '#313030',
        'surface': '#131313',
        'primary-fixed-dim': '#adc6ff',
        'inverse-surface': '#e5e2e1',
        'on-surface-variant': '#c2c6d6',
        'surface-container-high': '#2a2a2a',
        'outline': '#8c909f',
        'on-secondary-fixed-variant': '#005048',
        'secondary-fixed-dim': '#4fdbc8',
        'on-tertiary-fixed-variant': '#723600',
        'on-background': '#e5e2e1',
        'tertiary-fixed-dim': '#ffb786',
        'secondary-fixed': '#71f8e4',
        'on-tertiary': '#502400',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '40px',
        'gutter': '24px',
        'unit': '4px',
        'section-gap': '120px',
        'margin-mobile': '16px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'code': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'display': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'signature': ['Dancing Script', 'cursive'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'code': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '100% 0%' },
          '100%': { backgroundPosition: '-100% 0%' },
        },
        revealUp: {
          to: { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        shimmer: 'shimmer 4s infinite linear',
        revealUp: 'revealUp 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
    },
  },
  plugins: [],
};

export default config;